const noblox = require('noblox.js-proxy-agent');
const fs = require('fs').promises;
const path = require('path');

async function startApp() {
    try {
        const cookiePath = path.join(__dirname, 'cookies.txt');
        const cookie = await fs.readFile(cookiePath, 'utf8');
        const currentUser = await noblox.setCookie(cookie.trim()); 
        console.log(`Logged in as ${currentUser.UserName} [${currentUser.UserID}]`);

        const universe = await noblox.createUniverse({
            name: 'GENERATED GAME',
            description: 'generated by condogame.fun generator',
            isArchived: false,
            isFriendsOnly: false,
            isCopyingAllowed: false,
            genre: 'All'
        });
        console.log('Universe created:', universe);
        
        const place = await noblox.createPlace({
            name: 'generated',
            description: 'generated by condogame.fun generator',
            universeId: universe.universeId,
            isActive: true
        });
        console.log('Place created:', place);
        

        const gameFilePath = path.join(__dirname, 'test.rbxl');
        const gameFile = await fs.readFile(gameFilePath);
        const uploadResponse = await noblox.uploadPlace({
            placeId: place.placeId,
            data: gameFile
        });
        console.log('Game uploaded:', uploadResponse);
        
    } catch (error) {
        console.error('An error occurred:', error);
    }
}

startApp();
